<!DOCTYPE html>
<html>
    <head>
        <title>Observatory TBWA</title>

        <meta charset="UTF-8">
       
        <link rel="stylesheet" href="css/bootstrap.min.css" />
        <link rel="stylesheet" href="css/style.css" />
        <script src="js/jquery.min.js" type="text/javascript"></script>
        <script src="js/bootstrap.min.js" type="text/javascript"></script>
        <script src="js/validator.js" type="text/javascript"></script>
   
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
    <div id="cabecera">
    	<img src="../images/logo_header.png">
    </div>
            <div class="content-left">
                <div class="containers">
                    <div class="login">
                        <?php if(!$login){ ?>
                                    <a href="instalogin">Login in Instagram</a>                   
                            <?php } else { ?>
                                    <div class="profile-pic"><img height="100" weight="100" src="<?=$profile_picture?>" alt="" /></div>
                                    <h3><?=$username?></h3>
                                    <a href="logout">Logout</a>  
                         <?php }  ?>
                    </div>
                <?php if($error || $results['is_error'] == true) {?>
                        <div class="alert alert-danger">
                          <strong><?=$error_type?><?=$results['meta']['error_type']?></strong><?=$error_reason?><?=$results['meta']['error_message']?>
                        </div>
                <? } ?>
                <div class="row space">
                    <div class="headline">
                        <h2>Content Observatory</h2> <hr>
                        <p>Disruption App</p>
                    </div>
                </div>
                <? if($login) { ?>
                <div class="row">
                    <form name="getInst" id="instagramForm" method="POST" action="busca" data-toggle="validator" role="form">
                        <div class="row control-group">
                          <div class="form-group col-xs-6 floating-label-form-group controls">
                            <label>Tags</label>
                            <input class="form-control" placeholder="Tags" name="tag" id="tag" type="text" style="width:300px;" value="<?=$tag?>" />
                            <p class="help-block text-danger">Type by media tag, without #, separated by blank space" "</p>
                          </div>
                          <div class="form-group col-xs-6 floating-label-form-group controls">
                            <label>Username</label>
                            <input class="form-control" placeholder="Username" name="username" id="username" type="text" style="width:300px;" value="<?=$user?>" />
                            <p class="help-block text-danger">Type a username, without @, get Media recent by user</p>
                          </div>
                        </div>
                        <br>
                        <div id="success"></div>
                          <div class="form-group col-xs-4">
                            <button type="submit" class="btn btn-success btn-lg">Get Media !!</button>
                          </div>
                           <div class="form-group col-xs-8">
                            <a href="/" class="btn btn-lg">Clear</a>
                          </div> </form>
                 </div>
                   
                    <div class="row">
                        <div class="media">
                            <?php if($_POST) {if(!empty($results['data'])){ foreach($results['data'] as $media) { ?>
                                <div class="media-item">
                                    <div class="photo"><img src="<?=$media['images']['low_resolution']['url']?>" alt="" /></div>
	
                                        <p class="galeria-user">@<?=$media['user']['username']?></p>
                                        <p class="galeria-caption"><?=$media['caption']['text']?></p>
                                        <p><a href="<?=$media['link']?>" target="_blank"><?=$media['link']?></a></p>				
				 </div>
                            <? } } else { ?>
                            <div class="alert alert-warning" style="width: 100%;">
                                 <strong>No Data</strong> results, try another input data.
                            </div>
                            <? } } ?>
                         </div>
                    </div>
                          <? } ?>
                   <!--
                    <pre>
                        <?php // print_r($results); ?>
                    </pre> 
                   -->
                </div>
                </div>
            </div>
        </div>
        </div>
        <script type="text/javascript">
            $(document).ready(function(){
                $('#tag').click(function(){
                    $(this).removeAttr('disabled');
                        $('#username').prop("disabled", true);  $('#username').val('');
                });
                $('#username').click(function(){
                    
                    $(this).removeAttr('disabled');
                        $('#tag').prop("disabled", true);$('#tag').val('');
                });
             });
        </script>
    </body>
</html>